version: '3'
services:
  graphkb_db:
    image: orientdb:3.0
    environment:
      # customize settings below
      ORIENTDB_ROOT_PASSWORD: root
    ports:
      - 2424:2424
      - 2480:2480
    networks:
      - app-network
    volumes:
      - source: ./databases/orientdb/data
        target: /orientdb/databases
        type: bind
      - source: ./databases/orientdb/backup
        target: /orientdb/backup
        type: bind
  graphkb_api:
    image: bcgsc/pori-graphkb-api:v3.12.2
    ports:
      - 8080:8080
    environment:
      GKB_DB_CREATE: 1
      GKB_DB_HOST: graphkb_db
      GKB_DB_NAME: graphkb
      GKB_KEYCLOAK_KEY_FILE: /keys/keycloak.key
      KEY_PASSPHRASE: ''
      # customize settings below
      GKB_CORS_ORIGIN: '^https://pori-demo\.bcgsc\.ca.*$$'
      GKB_DBS_PASS: root
      GKB_KEYCLOAK_URI: https://pori-demo.bcgsc.ca/auth/realms/PORI/protocol/openid-connect/token
    depends_on:
      - graphkb_db
    networks:
      - app-network
    restart: always
    volumes:
      - source: ./keys
        target: /keys
        type: bind
        read_only: true
  graphkb_client:
    image: bcgsc/pori-graphkb-client:v4.2.2
    environment:
      KEYCLOAK_REALM: PORI
      KEYCLOAK_CLIENT_ID: GraphKB
      # customize settings below
      API_BASE_URL: https://pori-demo.bcgsc.ca/graphkb-api
      KEYCLOAK_URL: https://pori-demo.bcgsc.ca/auth
      PUBLIC_PATH: /graphkb/
      IS_DEMO: 1 # Remove when non-demo deployment
    ports:
      - 5000:80
    depends_on:
      - graphkb_api
    networks:
      - app-network
    restart: always
  ipr_db:
    image: bcgsc/pori-ipr-demodb:v6.2.3
    restart: always
    environment:
      DATABASE_NAME: ipr_demo
      POSTGRES_USER: postgres
      READONLY_USER: ipr_ro
      SERVICE_USER: ipr_service
      PGDATA: /var/lib/postgresql/data/pgdata
      # customize settings below
      POSTGRES_PASSWORD: root
      READONLY_PASSWORD: root
      SERVICE_PASSWORD: root
    ports:
      - 5432:5432
    networks:
      - app-network
  ipr_api:
    image: bcgsc/pori-ipr-api:v6.2.3
    ports:
      - 8081:8080
    environment:
      IPR_DATABASE_HOSTNAME: ipr_db
      IPR_DATABASE_NAME: ipr_demo
      IPR_DATABASE_USERNAME: ipr_ro
      IPR_GRAPHKB_USERNAME: ipr_graphkb_link
      IPR_KEYCLOAK_KEYFILE: /keys/keycloak.key
      # customize settings below
      IPR_DATABASE_PASSWORD: root
      IPR_GRAPHKB_PASSWORD: ipr_graphkb_link
      IPR_GRAPHKB_URI: https://pori-demo.bcgsc.ca/graphkb-api/api # http://graphkb_api:8080/api
      IPR_KEYCLOAK_URI: https://pori-demo.bcgsc.ca/auth/realms/PORI/protocol/openid-connect/token # http://localhost:8888/auth/realms/PORI/protocol/openid-connect/token
    depends_on:
      - ipr_db
    networks:
      - app-network
    restart: always
    volumes:
      - source: ./keys
        target: /keys
        type: bind
        read_only: true
  ipr_client:
    image: bcgsc/pori-ipr-client:v6.2.1
    environment:
      KEYCLOAK_REALM: PORI
      # customize settings below
      API_BASE_URL: https://pori-demo.bcgsc.ca/ipr-api/api # http://ipr_api:8081/api
      GRAPHKB_URL: https://pori-demo.bcgsc.ca/graphkb # http://graphkb_client:5000
      KEYCLOAK_URL: https://pori-demo.bcgsc.ca/auth # http://localhost:8888/auth
      PUBLIC_PATH: /ipr/
      IS_DEMO: 1 # Remove when non-demo deployment
    ports:
      - 3000:80
    depends_on:
      - ipr_api
    networks:
      - app-network
    restart: always
networks:
  app-network:
    driver: bridge
