site_name: PORI
theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.instant
repo_url: https://github.com/bcgsc/pori
repo_name: github
site_dir: dist
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.extra
  - attr_list
  - markdown_include.include:
      base_path: docs
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
extra_javascript:
  - js/mathjax.config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css: [styles.css]
plugins:
  - exclude:
      glob:
        - auth.md
        - _pori*
        - ipr/includes/*
  - awesome-pages
  - search
  - include-markdown
  - mknotebooks
  - redirects:
      redirect_maps:
          graphkb/scripting/intro_tutorial.md: graphkb/scripting/Intro_Tutorial.ipynb
nav:
  - Home: index.md
  - install.md
  - repos.md
  - demo.md
  - faq.md
  - ... | graphkb/**
  - ... | ipr/**
  - ... | variant_notation/**
  - ... | developer_reference/**
