name: build

on:
  - push


jobs:
  docker:
    runs-on: ubuntu-latest
    name: docker build
    steps:
      - uses: actions/checkout@v2
      - name: build the keycloak docker container
        run: |
          docker build --file Dockerfile.auth --tag bcgsc/pori-auth .
